library(ggplot2)
library(rworldmap)
library(ggmap)
library(gridExtra)
test<- read.csv("~/Dropbox/AfSIS_reporting_data/Seperated_datasets/Ldsf_field_details_SSN.csv")
aa <- ggplot(data=test.1, aes(x=Longitude,y=Latitude)) + geom_point(colour="red") + ggtitle("One sentinel site sampling")
a<-with(test,min(na.omit(Longitude)))
b<-with(test,max(na.omit(Longitude)))
c<-with(test,min(na.omit(Latitude)))
d<-with(test,max(na.omit(Latitude)))

newmap <- getMap(resolution="li")
newmap0<-subset(newmap,newmap@data$SOVEREIGNT=="Kenya"|newmap@data$SOVEREIGNT=="Uganda")
kiha<-read.csv("~/Studies_data/CIAT_best_loc.csv")

setwd("~/Studies_data/")         
png(file="AfSIS with CIAT points .png",height=600,width=600)
plot(newmap0)#,xlim=c(a,b),ylim=c(c-5,d+20))
test<-subset(test,test$Country=="Kenya"|test$Country=="Uganda")
with(test,points(Longitude,Latitude,col="blue",pch=19,cex=0.6))
with(kiha,points(Longitude,Latitude,col="red",pch=19,cex=0.6))
text(38,2,"Kenya",col="Grey",cex=1.4)
text(32,-0.5,"Uganda",col="Grey",cex=1.4)
text(35,-3,"CIAT",col="red",cex=1.4)
text(35,-2.5,"AfSIS",col="blue",cex=1.4)
points(34.0,-2.5,col="blue",pch=19,cex=0.8)
points(34.0,-3.0,col="red",pch=19,cex=0.8)
dev.off()
